### PR TITLE
feat: add env variables

### PR DESCRIPTION
**Pull request by Olyno**
# Description

This pull request adds env variable for a more flexible deployment and usage.

Feel free to tell me if it would be pertinent to have the same thing for the contract address.

### CODE REVIEW

**Comment by hazae41** [comment]
Please also add contract and chainId thanks

**Comment by hazae41** [comment]
* with default value

**Comment by Olyno** [comment]
Would you prefer not having errors and having default values instead?

**Comment by hazae41** [comment]
Yes for contract and chain please

**Pull request merged**
